services:
    alphaedge__market_data_producer:
        profiles: ["market-data-producer"]
        image: alphaedge__market_data_producer:latest
        container_name: alphaedge__market_data_producer
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        env_file:
            - .env
        ports:
            - "8005:8005"
        depends_on:
            alphaedge__rabbitmq:
                condition: service_healthy
        networks:
            - alphaedge__network
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 256M
                reservations:
                    cpus: "0.5"
                    memory: 128M

    alphaedge__rabbitmq:
        profiles: ["market-data-producer"]
        image: rabbitmq:3-management
        container_name: alphaedge__rabbitmq
        ports:
            - "5672:5672" # AMQP protocol port
            - "15672:15672" # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        restart: always
        networks:
            - alphaedge__network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 256M

    alphaedge__clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: alphaedge__clickhouse
        ports:
            - "8123:8123"
            - "9000:9000" # Native ClickHouse protocol port
        environment:
            - CLICKHOUSE_DB=${CLICKHOUSE_DB}
            - CLICKHOUSE_USER=${CLICKHOUSE_USER}
            - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
            - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - clickhouse_logs:/var/log/clickhouse-server
        networks:
            - alphaedge__network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2G
                reservations:
                    cpus: "1"
                    memory: 1G
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

networks:
    alphaedge__network:
        external: true

volumes:
    clickhouse_data:
    clickhouse_logs:
